services:
  postgres:
    image: postgres:17
    container_name: surebet-postgres
    environment:
      POSTGRES_DB: surebet
      POSTGRES_USER: surebet
      POSTGRES_PASSWORD: surebet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U surebet -d surebet"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: surebet-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: surebet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend-api:
    build:
      context: ../backend
      target: api
    container_name: surebet-backend-api
    environment:
      APP_NAME: surebet-platform
      APP_ENV: development
      HTTP_ADDRESS: :8080
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDRESS: redis:6379
      POSTGRES_DSN: postgres://surebet:surebet@postgres:5432/surebet?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"

  backend-worker:
    build:
      context: ../backend
      target: worker
    container_name: surebet-backend-worker
    environment:
      APP_NAME: surebet-platform
      APP_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDRESS: redis:6379
      POSTGRES_DSN: postgres://surebet:surebet@postgres:5432/surebet?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  laravel-data:
    build:
      context: ../laravel
    container_name: surebet-laravel-data
    profiles:
      - tools
    environment:
      APP_NAME: "Surebet Data Tools"
      APP_ENV: local
      APP_KEY: base64:wrSe80jPSZVHw+HaX0TLgZSwtJcA+6/NXZypXD7vaq4=
      APP_DEBUG: "true"
      APP_TIMEZONE: Asia/Ho_Chi_Minh
      APP_LOCALE: vi
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_DATABASE: surebet
      DB_USERNAME: surebet
      DB_PASSWORD: surebet
      ODDS_RETENTION_ACTIVE_HOURS: "24"
      ODDS_RETENTION_FINISHED_MINUTES: "30"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["php", "artisan", "list"]

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
